-- ===================== USUARIO =====================
CREATE TABLE USUARIO (
                         USUARIO_ID        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         NOME_COMPLETO     VARCHAR2(120)    NOT NULL,
                         CPF               CHAR(11)        NOT NULL,
                         DATA_NASCIMENTO   DATE            NULL,
                         EMAIL             VARCHAR2(150)    NOT NULL,
                         SENHA_HASH        VARCHAR2(256)    NOT NULL,
                         SENHA_SALT        VARCHAR2(128)    NOT NULL,
                         APPLY_CLICKS_HOJE NUMBER(10)         DEFAULT 0 NOT NULL,
                         JOBS_VIEWED_HOJE  NUMBER(10)         DEFAULT 0 NOT NULL,
                         ULTIMO_EVENTO_EM  TIMESTAMP       NULL,
                         CRIADO_EM         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         ATUALIZADO_EM     TIMESTAMP       NULL,
                         CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL),
                         CONSTRAINT UQ_USUARIO_CPF   UNIQUE (CPF),
                         CONSTRAINT CK_USUARIO_CPF_DIGITOS CHECK (REGEXP_LIKE(CPF, '^[0-9]{11}$')),
                         CONSTRAINT CK_USUARIO_EMAIL_FMT    CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'))
);

CREATE INDEX IX_USUARIO_CRIADOEM ON USUARIO (CRIADO_EM);


-- ===================== CURRICULO =====================
CREATE TABLE CURRICULO (
                           CURRICULO_ID   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           USUARIO_ID     NUMBER(19)         NOT NULL,
                           TIPO           VARCHAR2(10)    NOT NULL,   -- 'PDF' | 'TEXTO'
                           NOME_ARQUIVO   VARCHAR2(200)   NULL,
                           TAMANHO_BYTES  NUMBER(19)         NULL,
                           ARQUIVO_URL    VARCHAR2(500)   NULL,       -- se armazenar em blob/object storage
                           TEXTO          CLOB           NULL,       -- texto extraído/colado
                           STATUS         VARCHAR2(20)    DEFAULT 'PROCESSADO' NOT NULL, -- ENVIADO|PROCESSADO|ERRO
                           ANALISADO_EM   TIMESTAMP      NULL,
                           CRIADO_EM      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           CONSTRAINT FK_CURRICULO_USUARIO FOREIGN KEY (USUARIO_ID)
                               REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE,
                           CONSTRAINT CK_CURRICULO_TIPO CHECK (TIPO IN ('PDF','TEXTO')),
                           CONSTRAINT CK_CURRICULO_STATUS CHECK (STATUS IN ('ENVIADO','PROCESSADO','ERRO'))
);

CREATE INDEX IX_CURRICULO_USUARIO ON CURRICULO (USUARIO_ID, CRIADO_EM DESC);


-- ===================== VAGA =====================
CREATE TABLE VAGA (
                      VAGA_ID        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      TITULO         VARCHAR2(120)   NOT NULL,
                      EMPRESA        VARCHAR2(120)   NULL,
                      CIDADE         VARCHAR2(100)   NULL,
                      SENIORIDADE    VARCHAR2(40)    NULL,   -- ex.: JUNIOR/PLENO/SENIOR (texto livre)
                      DESCRICAO      CLOB           NULL,
                      REQ_MUST       CLOB           NULL,
                      REQ_NICE       CLOB           NULL,
                      ATIVA          CHAR(1)        DEFAULT 'S' NOT NULL, -- S|N
                      CRIADA_EM      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      CONSTRAINT CK_VAGA_ATIVA CHECK (ATIVA IN ('S','N'))
);

CREATE INDEX IX_VAGA_ATIVA ON VAGA (ATIVA);
CREATE INDEX IX_VAGA_CRIADAEM ON VAGA (CRIADA_EM);


-- ===================== CANDIDATURA =====================
CREATE TABLE CANDIDATURA (
                             CANDIDATURA_ID  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             USUARIO_ID      NUMBER(19)        NOT NULL,
                             VAGA_ID         NUMBER(19)        NOT NULL,
                             APLICADA_EM     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             STATUS          VARCHAR2(20)   DEFAULT 'ENVIADA' NOT NULL, -- ENVIADA|SALVA|ENTREVISTA|RECUSADA|APROVADA
                             SCORE_MATCH     NUMBER(10)       NULL,  -- 0..100
                             WHY_ME          VARCHAR2(400)  NULL,  -- resumo curto (bullets sintetizados)
                             APPLY_URL       VARCHAR2(500)  NULL,  -- link externo (LinkedIn/Indeed), se usado
                             CONSTRAINT FK_CAND_USUARIO FOREIGN KEY (USUARIO_ID)
                                 REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE,
                             CONSTRAINT FK_CAND_VAGA FOREIGN KEY (VAGA_ID)
                                 REFERENCES VAGA(VAGA_ID) ON DELETE CASCADE,
                             CONSTRAINT UQ_CAND_USR_VAGA UNIQUE (USUARIO_ID, VAGA_ID),
                             CONSTRAINT CK_CAND_STATUS CHECK (STATUS IN ('ENVIADA','SALVA','ENTREVISTA','RECUSADA','APROVADA')),
                             CONSTRAINT CK_CAND_SCORE  CHECK (SCORE_MATCH IS NULL OR (SCORE_MATCH BETWEEN 0 AND 100))
);

CREATE INDEX IX_CAND_USUARIO_APLICADAEM ON CANDIDATURA (USUARIO_ID, APLICADA_EM DESC);
CREATE INDEX IX_CAND_VAGA ON CANDIDATURA (VAGA_ID);


-- ===================== NOTIFICACAO =====================
CREATE TABLE NOTIFICACAO (
                             NOTIFICACAO_ID  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             USUARIO_ID      NUMBER(19)         NOT NULL,
                             TITULO          VARCHAR2(120)   NOT NULL,
                             MENSAGEM        VARCHAR2(500)   NOT NULL,
                             LIDO            CHAR(1)        DEFAULT 'N' NOT NULL, -- S|N
                             CRIADO_EM       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             CONSTRAINT FK_NOTIF_USUARIO FOREIGN KEY (USUARIO_ID)
                                 REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE,
                             CONSTRAINT CK_NOTIF_LIDO CHECK (LIDO IN ('S','N'))
);

CREATE INDEX IX_NOTIF_USUARIO_LIDO ON NOTIFICACAO (USUARIO_ID, LIDO, CRIADO_EM DESC);
